AllCops:
  Include:
    - '*.gemspec'
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - tmp/**/*

SymbolArray:
  Enabled: true

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 16

Documentation:
  Enabled: false
