AllCops:
  TargetRubyVersion: 2.2
  Include:
    - '*.gemspec'
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - tmp/**/*

SymbolArray:
  Enabled: true

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 16

Documentation:
  Enabled: false

Lint/Eval:
  Exclude:
    - 'spec/support/capture.rb'

Metrics/AbcSize:
  Max: 25

Metrics/ClassLength:
  Exclude:
    - 'lib/antwort/cli/cli.rb'
